Repository browniebroke/django-codemod, pull requests merged in 2020-05, with the labels that each got.

#2 Fix ForceTextToStrCommand when other imports are present in the file
  django_codemod/codemods/django_40.py
  tests/codemods/test_django_40.py
Labels: bug

#7 Move deployment to a separate stage
  .travis.yml
Labels: nochangelog

#8 Refactor checks to use matchers
  django_codemod/codemods/django_40.py
Labels: enhancement

#10 Support smart_text deprecation, replace by smart_str
  README.rst
  django_codemod/commands/django_40.py
  tests/commands/test_django_40.py
Labels: enhancement

#12 Support resolving django.utils.translation.ugettext deprecation
  README.rst
  django_codemod/commands/django_40.py
  tests/commands/test_django_40.py
Labels: enhancement

#13 Rename commands to reflect the functions they work with
  README.rst
  django_codemod/commands/django_40.py
  docs/usage.md
  tests/commands/test_django_40.py
Labels: breaking

#14 Support resolving django.utils.translation.ugettext_lazy deprecation
  README.rst
  django_codemod/commands/django_40.py
  tests/commands/test_django_40.py
Labels: enhancement

#15 Support resolving django.utils.translation.ugettext_noop deprecation
  README.rst
  django_codemod/commands/django_40.py
  tests/commands/test_django_40.py
Labels: enhancement

#16 Support resolving django.utils.translation.ungettext deprecation
  README.rst
  django_codemod/commands/django_40.py
  tests/commands/test_django_40.py
Labels: enhancement

#17 Support resolving django.utils.translation.ungettext_lazy deprecation
  README.rst
  django_codemod/commands/django_40.py
  tests/commands/test_django_40.py
Labels: enhancement

#18 Remove unused entry point
  django_codemod/cli.py
  requirements-dev.txt
  setup.py
  tests/test_cli.py
Labels: removed

#19 Migrate package metadata to declarative syntax
  setup.cfg
  setup.py
Labels: enhancement

#21 Fix some refs in README
  README.rst
Labels: documentation

#22 Support resolving django.conf.urls.url() deprecation
  README.md
  django_codemod/commands/django_40.py
  tests/commands/test_django_40.py
Labels: enhancement

#25 Resolve deprecation for django.shortcuts.render_to_response()
  django_codemod/commands/django_30.py
  tests/commands/test_django_30.py
Labels: enhancement

#27 Document how to list all available codemodders
  docs/usage.md
Labels: documentation

#28 Add missing description for URLToRePathCommand
  django_codemod/commands/django_40.py
Labels: documentation

#32 Refactor BaseSimpleFuncRename to simplify implementing new codemod
  django_codemod/commands/base.py
  django_codemod/commands/django_30.py
  django_codemod/commands/django_40.py
Labels: enhancement

#33 Document list of codemodders with autodoc
  .pre-commit-config.yaml
  Makefile
  README.md
  django_codemod/commands/django_30.py
  django_codemod/commands/django_31.py
  django_codemod/commands/django_32.py
  django_codemod/commands/django_40.py
  docs/_static/.gitkeep
  docs/codemods.rst
  docs/index.rst
  docs/usage.md
  requirements-dev.txt
Labels: documentation

#36 Refactor & move main logic from commands to visitors
  django_codemod/commands/base.py
  django_codemod/commands/django_30.py
  django_codemod/commands/django_40.py
  django_codemod/visitors/__init__.py
  django_codemod/visitors/base.py
  django_codemod/visitors/django_30.py
  django_codemod/visitors/django_31.py
  django_codemod/visitors/django_32.py
  django_codemod/visitors/django_40.py
Labels: enhancement

#37 New commands to fix all deprecations for a given version of Django
  django_codemod/commands/django_30.py
  django_codemod/commands/django_40.py
  tests/commands/test_django_30.py
  tests/commands/test_django_40.py
Labels: enhancement

#38 Fix bug with lost alias when 'import as' is used
  django_codemod/visitors/base.py
  tests/commands/test_django_40.py
Labels: bug

#39 Fix bug with trailing comma when removed import is the last one
  django_codemod/visitors/base.py
  tests/commands/test_django_40.py
Labels: bug

#40 Run tests with Github actions
  .github/workflows/test.yml
  README.md
  setup.cfg
Labels: nochangelog

#43 Remove commands to fix single deprecations
  README.md
  django_codemod/commands.py
  django_codemod/commands/__init__.py
  django_codemod/commands/base.py
  django_codemod/commands/django_30.py
  django_codemod/commands/django_31.py
  django_codemod/commands/django_32.py
  django_codemod/commands/django_40.py
  docs/codemods.rst
  docs/index.rst
  docs/usage.md
  tests/commands/test_django_30.py
  tests/commands/test_django_40.py
  tests/visitors/base.py
Labels: removed

#44 Fix commands non-findable by libCST
  README.md
  django_codemod/commands/__init__.py
  django_codemod/commands/base.py
  django_codemod/commands/django_codemod.py
  docs/codemods.rst
  docs/usage.md
  tests/commands/test_django_30.py
  tests/commands/test_django_40.py
  tests/visitors/base.py
Labels: bug

#45 Add the `obj` argument to `InlineModelAdmin.has_add_permission()`
  django_codemod/commands/django_codemod.py
  django_codemod/visitors/django_30.py
  docs/codemods.rst
  tests/visitors/test_django_30.py
Labels: enhancement

#46 Fix InlineModelAdmin transformer with multiple base classes
  django_codemod/visitors/django_30.py
  requirements-dev.txt
  tests/visitors/test_django_30.py
Labels: bug

#49 Move duplicated visitors tests for base class
  tests/visitors/test_base.py
  tests/visitors/test_django_30.py
  tests/visitors/test_django_40.py
Labels: nochangelog

#54 Make sure the function to rename is imported before renaming
  django_codemod/visitors/base.py
  tests/visitors/test_base.py
Labels: bug

#55 Add a djcodemod CLI
  README.md
  django_codemod/cli.py
  docs/codemods.rst
  docs/index.rst
  docs/usage.md
  docs/usage.rst
  requirements-dev.txt
  setup.cfg
  tests/test_cli.py
Labels: enhancement

#57 Remove watchdog deps
  Makefile
  requirements-dev.txt
Labels: nochangelog

#58 Publish to PyPI via Github actions
  .github/workflows/publish-pypi.yml
  .travis.yml
Labels: nochangelog

#60 Make InlineHasAddPermissionsTransformer more robust
  django_codemod/visitors/django_30.py
  tests/visitors/test_django_30.py
Labels: enhancement

#64 Add new CLI option `--deprecated-in`
  .github/workflows/lint.yml
  README.md
  django_codemod/cli.py
  django_codemod/commands/django_codemod.py
  django_codemod/constants.py
  django_codemod/visitors/__init__.py
  django_codemod/visitors/admin.py
  django_codemod/visitors/django_31.py
  django_codemod/visitors/django_32.py
  django_codemod/visitors/encoding.py
  django_codemod/visitors/shortcuts.py
  django_codemod/visitors/translations.py
  django_codemod/visitors/urls.py
  docs/codemods.rst
  docs/usage.rst
  tests/test_cli.py
  tests/visitors/test_django_30.py
  tests/visitors/test_django_40.py
Labels: enhancement
