Repository browniebroke/django-codemod, pull requests merged in 2020-07, with the labels that each got.

#117 Add support for adding `on_delete` for `ForeignKey` and `OneToOneField`
  django_codemod/visitors/__init__.py
  django_codemod/visitors/models.py
  tests/test_cli.py
  tests/visitors/test_models.py
Labels: enhancement

#126 Fix bug with CLI processing entire filesystem
  django_codemod/cli.py
Labels: bug

#131 Split tests and docs requirements
  .github/workflows/lint.yml
  .github/workflows/test.yml
  docs/requirements.in
  docs/requirements.txt
  requirements.in
  requirements.txt
Labels: tests

#130 Upload coverage report using codecov action
  .github/workflows/test.yml
Labels: tests

#139 Rename constants for numerical sorting
  django_codemod/constants.py
  django_codemod/visitors/admin.py
  django_codemod/visitors/decorators.py
  django_codemod/visitors/encoding.py
  django_codemod/visitors/html.py
  django_codemod/visitors/http.py
  django_codemod/visitors/lru_cache.py
  django_codemod/visitors/models.py
  django_codemod/visitors/os_utils.py
  django_codemod/visitors/shortcuts.py
  django_codemod/visitors/translations.py
  django_codemod/visitors/urls.py
Labels: enhancement

#148 Auto-update pre-commit hooks
  .pre-commit-config.yaml
Labels: dependencies

#123 Add module rename support and URLResolversTransformer
  django_codemod/visitors/__init__.py
  django_codemod/visitors/base.py
  django_codemod/visitors/core.py
  docs/codemods.md
  tests/test_cli.py
  tests/visitors/test_base.py
  tests/visitors/test_core.py
Labels: enhancement

#138 Support replacing `url()` with simple patterns by `path()`
  .github/workflows/test.yml
  django_codemod/re.py
  django_codemod/visitors/base.py
  django_codemod/visitors/core.py
  django_codemod/visitors/decorators.py
  django_codemod/visitors/encoding.py
  django_codemod/visitors/html.py
  django_codemod/visitors/http.py
  django_codemod/visitors/lru_cache.py
  django_codemod/visitors/os_utils.py
  django_codemod/visitors/shortcuts.py
  django_codemod/visitors/translations.py
  django_codemod/visitors/urls.py
  docs/codemods.md
  tests/visitors/test_base.py
  tests/visitors/test_urls.py
Labels: enhancement

#155 Auto-update pre-commit hooks
  .pre-commit-config.yaml
Labels: dependencies

#157 Internal refactoring of CLI and test improvements
  django_codemod/cli.py
  django_codemod/commands.py
  tests/test_cli.py
  tests/visitors/base.py
Labels: tests

#156 Add CLI command to list all codemodders
  .github/workflows/lint.yml
  README.md
  django_codemod/cli.py
  django_codemod/visitors/admin.py
  django_codemod/visitors/base.py
  django_codemod/visitors/core.py
  django_codemod/visitors/decorators.py
  django_codemod/visitors/encoding.py
  django_codemod/visitors/html.py
  django_codemod/visitors/http.py
  django_codemod/visitors/lru_cache.py
  django_codemod/visitors/models.py
  django_codemod/visitors/os_utils.py
  django_codemod/visitors/shortcuts.py
  django_codemod/visitors/translations.py
  django_codemod/visitors/urls.py
  docs/codemods.md
  docs/usage.md
  setup.cfg
  tests/test_cli.py
Labels: enhancement
